//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAnQuan.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool nguoiChoi_48_Minh {
            get {
                return ((bool)(this["nguoiChoi_48_Minh"]));
            }
            set {
                this["nguoiChoi_48_Minh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string txtDiem1_48_Minh {
            get {
                return ((string)(this["txtDiem1_48_Minh"]));
            }
            set {
                this["txtDiem1_48_Minh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string txtDiemQuan1_48_Minh {
            get {
                return ((string)(this["txtDiemQuan1_48_Minh"]));
            }
            set {
                this["txtDiemQuan1_48_Minh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string txtDiem2_48_Minh {
            get {
                return ((string)(this["txtDiem2_48_Minh"]));
            }
            set {
                this["txtDiem2_48_Minh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string txtDiemQuan2_48_Minh {
            get {
                return ((string)(this["txtDiemQuan2_48_Minh"]));
            }
            set {
                this["txtDiemQuan2_48_Minh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string lbQuan1_48_Minh {
            get {
                return ((string)(this["lbQuan1_48_Minh"]));
            }
            set {
                this["lbQuan1_48_Minh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string lbQuan2_48_Minh {
            get {
                return ((string)(this["lbQuan2_48_Minh"]));
            }
            set {
                this["lbQuan2_48_Minh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public string txtThoiGian1_48_Minh {
            get {
                return ((string)(this["txtThoiGian1_48_Minh"]));
            }
            set {
                this["txtThoiGian1_48_Minh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public string txtThoiGian2_48_Minh {
            get {
                return ((string)(this["txtThoiGian2_48_Minh"]));
            }
            set {
                this["txtThoiGian2_48_Minh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string btnO0_48_Minh {
            get {
                return ((string)(this["btnO0_48_Minh"]));
            }
            set {
                this["btnO0_48_Minh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string btnO1_48_Minh {
            get {
                return ((string)(this["btnO1_48_Minh"]));
            }
            set {
                this["btnO1_48_Minh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string btnO2_48_Minh {
            get {
                return ((string)(this["btnO2_48_Minh"]));
            }
            set {
                this["btnO2_48_Minh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string btnO3_48_Minh {
            get {
                return ((string)(this["btnO3_48_Minh"]));
            }
            set {
                this["btnO3_48_Minh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string btnO4_48_Minh {
            get {
                return ((string)(this["btnO4_48_Minh"]));
            }
            set {
                this["btnO4_48_Minh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string btnO5_48_Minh {
            get {
                return ((string)(this["btnO5_48_Minh"]));
            }
            set {
                this["btnO5_48_Minh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string btnO6_48_Minh {
            get {
                return ((string)(this["btnO6_48_Minh"]));
            }
            set {
                this["btnO6_48_Minh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string btnO7_48_Minh {
            get {
                return ((string)(this["btnO7_48_Minh"]));
            }
            set {
                this["btnO7_48_Minh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string btnO8_48_Minh {
            get {
                return ((string)(this["btnO8_48_Minh"]));
            }
            set {
                this["btnO8_48_Minh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string btnO9_48_Minh {
            get {
                return ((string)(this["btnO9_48_Minh"]));
            }
            set {
                this["btnO9_48_Minh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string btnO10_48_Minh {
            get {
                return ((string)(this["btnO10_48_Minh"]));
            }
            set {
                this["btnO10_48_Minh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string btnO11_48_Minh {
            get {
                return ((string)(this["btnO11_48_Minh"]));
            }
            set {
                this["btnO11_48_Minh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool soNguoiChoi_48_Minh {
            get {
                return ((bool)(this["soNguoiChoi_48_Minh"]));
            }
            set {
                this["soNguoiChoi_48_Minh"] = value;
            }
        }
    }
}
